### ISSUE TITLE
Audio glitches on Ubuntu (only some users?)

### ISSUE THREAD

**Issue by BigweldIndustries** [GooseMod/OpenAsar#10]
When I use the application with the normal asar it works fine, but when I use the open one strange things happen. Sound in the program works as expected but when joining a call, the audio gets crusty. Not like quality crusty, but unlistenably crusty. I really like this as a solution, but I hope this can be resolved

**Comment by ThatOneCalculator** [comment]
@BigweldIndustries are you using PulseAudio or PipeWire?

**Comment by BigweldIndustries** [comment]
pulseaudio

**Comment by ThatOneCalculator** [comment]
> pulseaudio

Try switching to Pipewire, as Pulse is now being deprecated. Voice works fine for me on Pipewire.

**Comment by BigweldIndustries** [comment]
I have been having issues with that, whenever I switch to pipewire no output nor input devices work. if you are on a debian based distro, could you link me to a guide?

**Comment by ThatOneCalculator** [comment]
I'm on Arch, but are you specifically on a Debian based distro with no Ubuntu or an Ubuntu based distro?

**Comment by BigweldIndustries** [comment]
Ubuntu. Whenever I use ``pipewire-pulse`` as a service and run ``pactl info`` it fails. Also no audio works

**Comment by CanadaHonk** [comment]
Have potential fix, testing

**Comment by CanadaHonk** [comment]
@BigweldIndustries Please try latest release and see if it fixes

**Comment by Dyzean** [comment]
isn't ubuntu running GNOME Wayland by default? discord have some issue with wayland iirc.

**Comment by BigweldIndustries** [comment]
I managed to successfully switch to pipewire, and it works now. 

I did this: https://askubuntu.com/questions/1339765/replacing-pulseaudio-with-pipewire-in-ubuntu-20-04
but ``pactl info`` was still failing, so i ran ``systemctl --user --now enable pipewire pipewire-pulse`` and rebooted. It all worked then
