### ISSUE TITLE
Questions about CSS theming

### ISSUE THREAD

**Issue by k2helix** [GooseMod/OpenAsar#102]
Hi, I have a few questions regarding the CSS theming.

Where is CSS stored (path)? 
Can OpenAsar use a theme that has more than one file?

Thanks in advance

**Comment by CanadaHonk** [comment]
There isn't a CSS file but it's inside your settings.json (`%appdata%\discord\settings.json` for Windows, in `~/.config` for Linux). You can compile a theme, you probably want to find a .theme.css.

**Comment by k2helix** [comment]
I see, and how can I compile a .scss theme which has more than one file?

**Comment by CanadaHonk** [comment]
You can probably look it up for how to do it depending on your system.
