### ISSUE TITLE
Update install scripts

### ISSUE THREAD

**Issue by aubymori** [GooseMod/OpenAsar#104]
Hi. The install scripts seen on openasar.dev do not work because of Discord's new update from from 1.0.9006 to 1.0.9007. The fix is as simple as doing a Ctrl+H and replacing any instance of 1.0.9006 in the script with 1.0.9007. I would've made a pull request, but I can't seem to find any of these install scripts anywhere on your GitHub.

**Comment by CanadaHonk** [comment]
Fixed, they're in https://github.com/OpenAsar/openasar.github.io/blob/main/themes/hugo-html5up-alpha/layouts/partials/installer.html btw.
