### ISSUE TITLE
modules are not moved after discord update

### ISSUE THREAD

**Issue by Nama** [GooseMod/OpenAsar#106]
Hi,

I'm not sure if this is an issue with discord itself, or OpenAsar.
`discord` got updated on the arch repos from 0.0.20 to 0.0.21 and OpenAsar couldn't find the modules anymore, since those were still in the directory of 0.0.20.
I then renamed `~/.config/discord/0.0.20/` to `~/.config/discord/0.0.21/` and discord starts again.

Since discord is an app installed from the repos and the modules are in my home directory, this needs handling after the first start. This could also be an issue after a fresh install of discord and OpenAsar (without starting discord once in between). 

```
[OpenAsar > BuildInfo] { releaseChannel: 'stable', version: '0.0.21' }
[OpenAsar > Modules] Checking
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Error: Cannot find module '~/.config/discord/0.0.21/modules/discord_desktop_core'
```

**Comment by CanadaHonk** [comment]
You probably installed OpenAsar on the first start while having quick start enabled.

**Comment by Nama** [comment]
No, I installed OpenAsar long before this discord update.

**Comment by CanadaHonk** [comment]
You said it happened after the update? OpenAsar is uninstalled after your package manager updates Discord.

**Comment by Nama** [comment]
Well, OpenAsar was still installed. I didn't reinstall it.

**Comment by Nama** [comment]
It probably didn't got replaced, since the file is from another installed package.
If it is expected to reinstall OpenAsar on every update, then ya, this is expected.

Thank you!

**Comment by Fabian42** [comment]
I have the same problem, just updated from 0.0.32 to 0.0.33 and Discord no longer started. Moved the config folder and it worked again. I installed `openasar-git` from AUR. Reinstalling the package did not help, but that shouldn't be required anyway.

**Comment by Nama** [comment]
Ya, u need to uninstall openasar, start discord,close discord, install openasar again. Happened to me now again, too. First time since I wrote this issue^^

**Comment by Fabian42** [comment]
Is that supposed to be a requirement every time or a bug that only happened this time?

**Comment by Nama** [comment]
Seems to be a requirement or even a forced thing from the update, according to this comment:
https://github.com/GooseMod/OpenAsar/issues/106#issuecomment-1288181308
