### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by VenaxMaker** [GooseMod/OpenAsar#107]
Hello. I want to uninstall OpenAsar from my Windows computer. How can I do that?

Thanks in advance.

**Comment by CanadaHonk** [comment]
See: https://github.com/GooseMod/OpenAsar/wiki/Install-Guide

(GitHub Issues isn't the best for support btw, use the Discord in future as it's easier and intended.)

**Comment by VenaxMaker** [comment]
sorry! i'll use Discord next time.
