### ISSUE TITLE
Mistake in Wiki

### ISSUE THREAD

**Issue by ThatOneCalculator** [GooseMod/OpenAsar#11]
![Screenshot_2022-01-12-01-17-47_2560x1440](https://user-images.githubusercontent.com/44733677/149222830-01d26df3-9bd4-41cc-93c9-17ef72fc748e.png)

After some debate in the Discord, it seems changing the line

> Linux: depends on how you installed, find your exe I guess

to

> Linux: most likely `/opt/discord/resources/app.asar`, however, this may vary based on your installation method

would be a good idea.

**Comment by CanadaHonk** [comment]
Issues isn't for Wiki, just the project itself. Please keep to Discord.
