### ISSUE TITLE
[AsarUpdate] Improve error response resilience

### ISSUE THREAD

**Issue by DeGamersSpelen** [GooseMod/OpenAsar#112]
I restarted discord and magically it wouldn't open...

Opened app.asar with notepad++ and saw this:

\<?xml version="1.0" encoding="utf-8"?>\<Error>\<Code>ServerBusy\</Code>\<Message>Egress is over the account limit.
RequestId:8f153c3c-301e-002f-0cc8-f82fae000000
Time:2022-11-15T08:01:48.3187599Z\</Message>\</Error>

So OpenAsar replaced my OpenAsar with a xml error because my internet wasn't working.

**Comment by DeGamersSpelen** [comment]
I suggest there should be error checking.

**Comment by avail** [comment]
https://github.com/GooseMod/OpenAsar/blob/main/src/updater/updater.js#L85
Feel free to add a handler for ServerBusy cases.

**Comment by CanadaHonk** [comment]
Done in 0b1d4685cb2c94f42441fc616eb24e69eda04647.
