### ISSUE TITLE
[Feature request] Disable autoupdate

### ISSUE THREAD

**Issue by sapphonie** [GooseMod/OpenAsar#114]
I'd really like to not have potentially untrusted software autoupdate itself, at least without getting the chance to review what's changed, Powercord/Replugged did a a great job of this [showing commit hash + commit messages], could something similar be implemented here? Or at least, a flag to toggle it. Don't want to futz with permissions to hack it off, lol

**Comment by CanadaHonk** [comment]
It's already something you can set in OpenAsar's config, just isn't documented. Set `"autoupdate": false` in OpenAsar's config (`%appdata%\discord\settings.json` / `~/.config/discord/settings.json` / etc).
