### ISSUE TITLE
[Linux] Fix pipewire/wayland screen sharing?

### ISSUE THREAD

**Issue by Sukid** [GooseMod/OpenAsar#118]
Electron supports it and it seems to work just fine with something like webcord, so there must be something up in discord itself that isn't working so well with it. 
[This is a wrapper hack](https://gist.github.com/Vendicated/5e5eee64348ee936349367fe7cedd8c3) that fixes it on some versions of electron at least. I haven't had much luck with electron 20 but this might serve as an important reference for fixing it fully in OpenAsar if someone wants to take that challenge. (sadly i lack the expertise or I would be doing it. :( )

**Comment by CanadaHonk** [comment]
Not related to app.asar, so out of scope / wrong place.
