### ISSUE TITLE
[Suggestion] anti index.js modifier

### ISSUE THREAD

**Issue by ilyigna** [GooseMod/OpenAsar#120]
Some token grabbers every time when the Discord client is started, it loads a custom index.js that's something like [this](https://github.com/KSCHdsc/BlackCap-Inject) which sends some info, as well some of them even fetch credit cards (when they're added)

an example to "avoid" getting index.js modified would've this (copied from [this Reddit comment](https://www.reddit.com/r/discordapp/comments/gx702s/how_to_prevent_discord_malware/?sort=confidence)
```js
const fs = require('fs');

(() => {
    fs.watch(_path.join(__dirname, '../../'), (e, filename) => {
        if (filename !== 'index.js') return;

        const indexPath = _path.join(__dirname, '../../index.js');

        _fs.writeFileSync(indexPath, "module.exports = require('./core.asar');");
    });
})();
```

**Comment by lexisother** [comment]
Pretty sure this is outside of the scope of the project.

**Comment by ilyigna** [comment]
> Pretty sure this is outside of the scope of the project.

well yeah (not at all), tho ducko before wanted to add a anti tokengrabber iirc and this may would do the work a bit better

**Comment by Vendicated** [comment]
there's no point in doing this since it's a dumb cat and mouse game you can't win. Just don't run malware on your system

**Comment by CanadaHonk** [comment]
They could just modify the app.asar instead. Leaving for at least now.
