### ISSUE TITLE
[Bug] Discord (Canary) launches and freezes with a blank screen after a restart until OpenAsar is reinstalled

### ISSUE THREAD

**Issue by SomeCuteDoragons** [GooseMod/OpenAsar#126]
I use Discord Canary and whenever it fully restarts, be it by fully closing discord or restarting my PC, when Discord is launched it just shows a blank grey screen and does nothing else until I rerun the installation of OpenAsar.

**Comment by CanadaHonk** [comment]
Please use the support in our Discord instead of GitHub issues for assistance.

**Comment by SomeCuteDoragons** [comment]
Okay, sorry for the inconvenience!
