### ISSUE TITLE
You can open multiple openasar config windows [bug]

### ISSUE THREAD

**Issue by Ya-boy-Jotaro-KuJo** [GooseMod/OpenAsar#132]
here is a picture

![image](https://user-images.githubusercontent.com/116957464/229356985-1befc8be-9872-4a02-bcf9-c7d0dd6240f8.png)

you can also make them both different settings
![image](https://user-images.githubusercontent.com/116957464/229357173-492692f0-0777-45ff-8ad4-72312b1706af.png)

**Comment by miqumi** [comment]
# bro tell how to reproduce

**Comment by Ya-boy-Jotaro-KuJo** [comment]
> # bro tell how to reproduce

just click the open asar settings multiple times???

**Comment by CanadaHonk** [comment]
Fixed.
