### ISSUE TITLE
Where does openasar store configs?

### ISSUE THREAD

**Issue by miqumi** [GooseMod/OpenAsar#133]
# w e r e

**Comment by miqumi** [comment]
just the question

**Comment by CanadaHonk** [comment]
The same file as Discord (`%appdata\discord\settings.json` etc). Use our Discord server for support instead of GitHub.

**Comment by miqumi** [comment]
> The same file as Discord (`%appdata\discord\settings.json` etc). Use our Discord server for support instead of GitHub.

okie
