### ISSUE TITLE
Duplicate OpenAsar Setting Tabs

### ISSUE THREAD

**Issue by Snare-Hawk** [GooseMod/OpenAsar#135]
Upon opening different tabs in the settings page, OpenAsar duplicates itself every time.

```
Stable 185832 (29333f6)
Host 1.0.9012 (30921)
OpenAsar Nightly (28e8ed4)
Windows 10 64-Bit (10.0.19044)
Replugged [DEV MODE]
```
https://user-images.githubusercontent.com/85657152/229664259-0423fa44-9f4b-4bb7-8ef5-ec73cc987001.mp4

**Comment by Ya-boy-Jotaro-KuJo** [comment]
this is a replugged issue not an openasar issue please open it in their repository

**Comment by Ya-boy-Jotaro-KuJo** [comment]
i dont know much about replugged but according to you its a dev mod replugged (im guessing like a canary thingy?)

**Comment by lexisother** [comment]
> this is a replugged issue not an openasar issue please open it in their repository

Not a Replugged issue.

**Comment by TMJOJO** [comment]
> > this is a replugged issue not an openasar issue please open it in their repository
> 
> Not a Replugged issue.

can you replicate while not using replugged?

**Comment by lexisother** [comment]
No, but it does further solidify my point that the way OpenAsar is adding its menu is hacky and has issues. Replugged can do nothing to fix it.

**Comment by TMJOJO** [comment]
> Upon opening different tabs in the settings page, OpenAsar duplicates itself every time.
> 
> ```
> Stable 185832 (29333f6)
> Host 1.0.9012 (30921)
> OpenAsar Nightly (28e8ed4)
> Windows 10 64-Bit (10.0.19044)
> Replugged [DEV MODE]
> ```

also newest version of openasar is const element = document.getElementsByClassName("backdrop-2ByYRN withLayer-2VVmpp");

  while (element.length > 0) element[0].remove();

**Comment by TMJOJO** [comment]
not 28e8ed4

**Comment by TMJOJO** [comment]
> No, but it does further solidify my point that the way OpenAsar is adding its menu is hacky and has issues. Replugged can do nothing to fix it.

literally doesnt help that this only happens if you have replugged i have bd and nothing happens

**Comment by CanadaHonk** [comment]
GitHub issues is not for conversation or debate, no further helpful info can be added, so refrain from posting.
