### ISSUE TITLE
OpenAsar settings button is duplicated with Replugged installed

### ISSUE THREAD

**Issue by Leo40Git** [GooseMod/OpenAsar#137]
This bug was already mentioned on the server multiple times, just submitting it as an issue so it doesn't get forgotten about.

**Comment by Tharki-God** [comment]
this can be fixed by adding a extra property on open asar tab and if the element with that property already exists then don't add it

**Comment by CanadaHonk** [comment]
Already done, not an OpenAsar related issue.

**Comment by Tharki-God** [comment]
just add an extra class with addClass like `oa` and then check with this selector if it exists if yes then just return `document.querySelector('[class*="socialLinks-"]').parentElement.querySelector('.oa')`

**Comment by CanadaHonk** [comment]
This was fixed
