### ISSUE TITLE
Bug(?) Report On Currenty Nightly (20b5fa3)

### ISSUE THREAD

**Issue by MonfGeiger** [GooseMod/OpenAsar#139]
Sometimes i have to put my computer into safe mode to deal with driver issues (amd issues, sound card issues, etc....), and i had to do so again today, and i think i found a rather curious interaction with OpenAsar and Windows Safe Mode. It seems that whenever i put my computer into safe mode (using the bcdedit command-line arg `bcdedit /set safeboot minimal`) and then after im done return my computer to normal mode (again, using the bcdedit command-line arg `bcdedit /deletevalue safeboot`), the openasar settings for discord reset to default, like i'm using it for the first time (splash theme option on, no track on), and it also sets the "minimize to sys tray" windows setting to off instead of leaving it on. thankfully this bug(?) doesn't affect ANY other discord setting whatsoever, just the one normie discord setting and OpenAsar settings

I am relatively sure this is not solely a discord only issue and is an interaction with OpenAsar, Discord, and Windows combined. If such is proven otherwise though......idk what to say really :/

**Comment by CanadaHonk** [comment]
Electron bug most probably.
