### ISSUE TITLE
new update made it just occationally not show the openasar button, and themes dont load

### ISSUE THREAD

**Issue by jqms** [GooseMod/OpenAsar#141]

**Comment by CanadaHonk** [comment]
System/discord/setup info and steps to reproduce?

**Comment by jqms** [comment]
i said occationally. cant reproduce because its seeminly random

window 10
stable
i dont understand setup info

**Comment by BK8000L** [comment]
same

**Comment by Xseba360** [comment]
same happened today, seems to be related to discord updates
these aren't really steps for a proper repro but it goes somewhat like this:

1. a discord update button appears
2. shutdown system (windows 10)
3. after logging in, openasar seems to be 'gone' and have to reinstall it.

**Comment by BK8000L** [comment]
i don't need to reinstall openasar, restarting discord makes it work again

**Comment by jqms** [comment]
just happened after i updated discord, but after a full app restart it fixed itself

**Comment by BK8000L** [comment]
didn't happen when i updated discord by clicking "update ready!"
