### ISSUE TITLE
No "resources/app.asar" What do I do?

### ISSUE THREAD

**Issue by SylvKT** [GooseMod/OpenAsar#143]
I don't appear to have a `.../discord-canary/resources` directory. Instead, this is what the file structure looks like:
![image](https://github.com/GooseMod/OpenAsar/assets/18603248/c89c792f-9f18-4c44-bf41-510cecca484f)
```
app.asar  app.asar.unpacked  bootstrap  build_info.json
```
This means I can't install it correctly. Where would I locate this? I've installed Discord Canary via the [`discord-canary-electron-bin`](https://aur.archlinux.org/packages/discord-canary-electron-bin)<sup>AUR</sup> which may be contributing to this issue.

**Comment by nonperforming** [comment]
Have you tried using these?
https://aur.archlinux.org/packages/openasar-all-git
https://aur.archlinux.aorg/packages/openasar-bin
