### ISSUE TITLE
bug(?): typo/weird grammar in settings menu

### ISSUE THREAD

**Issue by Rexogamer** [GooseMod/OpenAsar#145]
Hey! 

I've noticed that, in the settings menu, the Splash Theming option's description reads "Themes splash screen the same as your client mod's". I'm assuming this is meant to be a plural (in which case it should probably read "Themes the splash screen to match your client mods"); if not, it should probably read something like "Uses your client mod's theme for the splash screen". 

I've tried to find the relevant code to submit a fix but it doesn't appear to be on GitHub? If it is and I've just missed it, feel free to point me to the relevant file(s) and I'll submit a PR.

Thanks for the great project, by the way :3

**Comment by CanadaHonk** [comment]
Thanks, done. It's at https://github.com/OpenAsar/cdn btw.
