### ISSUE TITLE
[Suggestion] One liner command that fetches the actual install script automatically

### ISSUE THREAD

**Issue by khanhmuy** [GooseMod/OpenAsar#146]
This would make it really easy to deploy OpenAsar with automatic scripts on new systems, and it would make it easier for less tech-savvy people to install OpenAsar, even if it's only realistically doable on Windows.

**Comment by GreenMan36** [comment]
Just `curl` the script you want `&&` run it.

**Comment by khanhmuy** [comment]
fair but putting it on the actual webpage would be easier for the user

**Comment by GreenMan36** [comment]
> fair but putting it on the actual webpage would be easier for the user

Two clicks is easier than a terminal ;)

**Comment by khanhmuy** [comment]
fair:)
