### ISSUE TITLE
blocked by cloudflare?

### ISSUE THREAD

**Issue by cozykitten** [GooseMod/OpenAsar#152]
When I started discord this morning, instead of the normal friend page I got a message saying access to discord.com was blocked by cloudflare.
![discord_wtf](https://github.com/GooseMod/OpenAsar/assets/116394977/f3859ad3-9b6d-4f83-bb2e-9b628ff9470b)

After I replaced openasar's app.asar with discord's app.asar it worked again.
Never had that issue before, and there wasn't any update from openasar, in the last days either, it really just happened out of the blue.

**Comment by CanadaHonk** [comment]
Discord bug happening to many people, unrelated. Use canary for now or wait and refresh.

**Comment by cozykitten** [comment]
Ah, thank you very much, sorry for opening an issue
