### ISSUE TITLE
Most recent installer triggers Windows Defender

### ISSUE THREAD

**Issue by ArcticTheRogue** [GooseMod/OpenAsar#157]
When trying to launch the most recent installer from openasar.dev windows defender gives this warning:
![image](https://github.com/GooseMod/OpenAsar/assets/58752937/7600052f-d3c5-462c-b0d6-b01d7d731995)

**Comment by CyanoTex** [comment]
[You might want to manually submit it to Microsoft for analysis.](https://www.microsoft.com/en-us/wdsi/filesubmission)

Requirements:
-Microsoft Account to log in to submit the file
-File in an encrypted ZIP with the password 'infected'
-Detection name
-Definition version - instructions [here](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus?view=o365-worldwide#definition-version) on how to get it

1. Go to the website and log in.
2. Pick Microsoft Defender Antivirus (10 if you're on Win10, 11 if you're on Win11).
3. Submit the encrypted ZIP with your file.
4. Choose "Incorrectly detected as malware/malicious".
5. Fill out "Detection name" and "Definition version".
6. Click "Continue", and confirm you put everything in correctly.
7. Fill out the CAPTCHA code and submit.

You'll be notified by email when they've received it and when they've finished the analysis, but you can also check on your submission through the URL you were given.

**Comment by ArcticTheRogue** [comment]
Thank you, from a quick test it seems it was fixed by MS at some point. Closing the issue.
