### ISSUE TITLE
BetterDiscord broken agian

### ISSUE THREAD

**Issue by binarynoise** [GooseMod/OpenAsar#159]
Like #72, betterdiscord won't install.

**Comment by themegaxandy** [comment]
It worked normally for me. I first installed OpenAsar, and then BetterDiscord. Try completely uninstalling Discord and BetterDiscord in %appdata%, %localappdata%, C:\ProgramData, and then installing everything again.

**Comment by binarynoise** [comment]
I cleaned the discord folder (I'm on Linux btw), this appeared on installing BD:

> Injecting shims...
Injecting into: /home/me/.config/discord/0.0.35/modules/discord_desktop_core
❌ Could not inject shims to /home/me/.config/discord/0.0.35/modules/discord_desktop_core
❌ ENOENT: no such file or directory, open '/home/me/.config/discord/0.0.35/modules/discord_desktop_core/index.js'

**Comment by CanadaHonk** [comment]
That error isn't related to OpenAsar (also please use Discord for support instead).

**Comment by binarynoise** [comment]
I found the reason. The discord-electron-openasar-git package from aur installed discord 0.0.25 instead of 0.0.35. What works is discord-canary-electron-bin together with openasar-bin + manually installing BD.
Sorry for the noise
