### ISSUE TITLE
[Request] scroll speed modifier

### ISSUE THREAD

**Issue by xeome** [GooseMod/OpenAsar#16]
Is it possible to include a scroll speed modifier? The scrolling speed of electron applications on Linux is excruciatingly slow. There are some solutions, such as imwheel, but they are too hacky (just sends multiple scroll events to increase speed). So, if it is possible to do so through the asar file, please let me know.

**Comment by CanadaHonk** [comment]
Not possible with just asar / Electron I'm pretty sure, apologies.
