### ISSUE TITLE
Suspected Memory Leak maybe?

### ISSUE THREAD

**Issue by SFGrenade** [GooseMod/OpenAsar#165]
Discord client details:
```
Stable 255832 (4d02ba6)
Host 1.0.9028 x86 (41936)
OpenAsar Nightly (1c24e09)
Windows 10 64-Bit (10.0.19044)
```
Problem:
When having discord open and in a video-chat (may just need to stay open), one of the discord-processes, uses more and more ram over time, i watched it climb from 450 MB to 522 and back to 460 and slowly climbing up again.

**Comment by CanadaHonk** [comment]
Discord, not OpenAsar.
