### ISSUE TITLE
OpenAsar keeps being removed

### ISSUE THREAD

**Issue by ividyon** [GooseMod/OpenAsar#166]
Anything that can be done about that? Basically every Discord update (which are extremely frequent) I have to reinstall this.

**Comment by CanadaHonk** [comment]
OpenAsar *tries* to automatically install itself into new host versions on Windows. Please use [the Discord](https://discord.com/invite/YDMptE8u2b) for support.

**Comment by Fabian42** [comment]
@CanadaHonk Discord is literally the only place in the world that should NOT be used for support of this program… That is like the classic "no keyboard detected, press F1 to continue".

**Comment by CanadaHonk** [comment]
You can use Discord in your browser.
