### ISSUE TITLE
Is it safe

### ISSUE THREAD

**Issue by CoderLogy** [GooseMod/OpenAsar#17]
I am asking this question to confirm that it's safe and free from any vulnerabilities so I could share with others and on my youtube channel and even use it thanks. Meaning I want to confirm that you are agree it does not have any type of vulnerability and you are liable for any loss of data or password etc

**Comment by RealTriassic** [comment]
OpenAsar is safe as far as I am aware, I have been using for over a month now and haven't had any issues with any vulnerabilities or anything like that.

**Comment by skittles9823** [comment]
I'd like to point you to the [licence](../blob/main/LICENSE) do note what it says under Limitations, and understand what open source software is.

**Comment by CanadaHonk** [comment]
To say officially, mostly yes but you cannot guarantee any software is fully safe. It should be as safe as normal Discord. There is no warranty / liability as under the MIT license. Thanks.

**Comment by CoderLogy** [comment]
oh that is a really fast response team thanks for the response but one more thing I am not able to see any themes or plugin option when I install it discord boots same like earlier

**Comment by CanadaHonk** [comment]
I'm just one person running it. Have you read the readme or repo? This isn't for plugins or themes. I recommend you read the website: https://openasar.github.io (and recommend you use it if you produce a video as it has an installer and info)

**Comment by CoderLogy** [comment]
Oh ok thanks for information 👍 hope this project goes far well

**Comment by CanadaHonk** [comment]
No problem, you can send a link if you end up making a video if you want. Thanks.
