### ISSUE TITLE
OpenAsar option not displayed in settings page on latest Discord client.

### ISSUE THREAD

**Issue by AlphaCraft9658** [GooseMod/OpenAsar#172]
On Discord version 0.0.40 on Fedora, I cannot find the option for opening the OpenAsar settings. This wasn't the case before.

**Comment by KraXen72** [comment]
reinstall it, it probably got removed during a discord update. it happens sometimes.

**Comment by AlphaCraft9658** [comment]
> reinstall it, it probably got removed during a discord update. it happens sometimes.

Even after reinstalling multiple times, the option is still not there. After removing the OpenAsar data directory, I get the welcome screen of OpenAsar, but the option is still not there.

**Comment by Roki100** [comment]
![image](https://github.com/GooseMod/OpenAsar/assets/35699619/299f8035-5bca-4b13-a591-70afadd5830f)
to access settings just press this little boy on the bottom of the setting tabs

**Comment by AlphaCraft9658** [comment]
> ![image](https://github.com/GooseMod/OpenAsar/assets/35699619/299f8035-5bca-4b13-a591-70afadd5830f)
> to access settings just press this little boy on the bottom of the setting tabs

Late reaction, but this is the solution. So the options just migrated from a dedicated button to a more hidden place. I am going to close this issue now.

**Comment by holiq** [comment]
> ![image](https://private-user-images.githubusercontent.com/35699619/305101465-299f8035-5bca-4b13-a591-70afadd5830f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjM4ODYsIm5iZiI6MTcyNTYyMzU4NiwicGF0aCI6Ii8zNTY5OTYxOS8zMDUxMDE0NjUtMjk5ZjgwMzUtNWJjYS00YjEzLWE1OTEtNzBhZmFkZDU4MzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDExNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZjFlNGJjNTY4OGIyZWNlOWYwZTVjOTU2NjU1YjQwYmRlZTliZDAwODA5YTVmZDAzOWM2MmMxMzMzZGJjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLKyD-3H2XsB-zeb3DcxuJOfKAkgIllV9Nq8XYaC7Yg) to access settings just press this little boy on the bottom of the setting tabs

finally i found it, i think it should add into readme for open the setting menu
