### ISSUE TITLE
Splash screen not downloading anything

### ISSUE THREAD

**Issue by cd-FileX** [GooseMod/OpenAsar#174]
I'm pretty sure, in a previous version it downloaded updates, but since a while it has just been showing "Skip" and "Quit".
Skip is not downloading anything, obviously, and quit does what it should.

I have been trying to update multiple times, but nothing has changed. Not even the number of days since the new update release.

Note: Maybe this is a sudo conflict.

![image](https://github.com/GooseMod/OpenAsar/assets/79639219/a380f4ab-3176-44f0-a296-b4df256a6d6c)

System: Kubuntu 23.10
Discord: Canary

**Comment by compguy284** [comment]
that is saying there is a new version of discord available. openasar does not update discord versions.
