### ISSUE TITLE
Can you teach or show or even tell how to install the plugins and themes

### ISSUE THREAD

**Issue by CoderLogy** [GooseMod/OpenAsar#18]
Sorry man for disturbing but yeah I needed help in that thing for figuring that out.

**Comment by CoderLogy** [comment]
yeah and plus it doesnot work I am not able to even install it

**Comment by CanadaHonk** [comment]
This repo is for OpenAsar, not GooseMod, separate projects. Join the Discord if you require support.

**Comment by CoderLogy** [comment]
ok ok but tell me i am not able to install open asar thnks bye
