### ISSUE TITLE
CSS importing

### ISSUE THREAD

**Issue by Sp3EdeR** [GooseMod/OpenAsar#190]
Hello OpenAsar devs!

So OpenAsar has a custom CSS support, and there are many premade CSS packages from theming to adblocking on github. They usually support Vencord and Better Discord, and they usually go for the `@import url(...)` API to ensure that the CSS can update with the Discord client dynamically. It seems to me that this syntax does not work with OpenAsar. I think it would be a very handy function.

My best guess for the reason of this issue is that the `@import url(...)` must appear at the start of the entire CSS file, before any CSS declarations. So perhaps by updating the CSS injection point, it might work?

**Comment by SmolAlli** [comment]
![image](https://github.com/user-attachments/assets/c43f1ec3-1bbe-4b28-ad81-1e4cfd1e0c29)
I can personally confirm that using import URLs does work
My theme comes from one and I have a snippet. It has always worked without issue.

**Comment by Sp3EdeR** [comment]
Can you please provide the links so that I can test with your themes?

**Comment by Sp3EdeR** [comment]
I think I found the issue. When the CSS is hosted on github pages, it seems to work fine. But from raw.githubusercontent.com, it does not seem to send proper response headers, and so Discord refuses to load it. Sorry for misidentifying the issue and thanks for the help!
