### ISSUE TITLE
[General] Complete rewrite

### ISSUE THREAD

**Issue by CanadaHonk** [GooseMod/OpenAsar#21]
Rewrite 100% of source, currently estimated at around 90% done. Mostly unneeded rewrites which will be a hassle to do cleanly like splash backend and some leftover updater parts.

Files left todo:
- [x] Splash backend
- [x] Module updater
- [ ] Updater v2 (win32 only)

**Comment by CanadaHonk** [comment]
Progress Update: Core of splash backend was rewritten a few days ago, only updater remnants remaining inside it.

**Comment by CanadaHonk** [comment]
Complete splash backend released yesterday, looks good.

**Comment by sergiorgb** [comment]
why updater win32 only?

**Comment by CanadaHonk** [comment]
Discord has two updaters, the "new" one remains win32 only. Other platforms use "old", hence module updater ("old") and updater ("new"). Same as internal names.

**Comment by CanadaHonk** [comment]
Self-rewritten module updater is pushed! Looks to be amazing. **Updating on Linux is 2-3x faster** due to new parallel downloading + installing as opposed to vanilla's queue. Also **reduced release size by 13kb**!

**Comment by CanadaHonk** [comment]
> linux only ?

Yes, as it's the module updater.

**Comment by CanadaHonk** [comment]
Already partially rewritten updater v2, just needs a bit more polish / further rewriting. ETA ~23rd?

**Comment by CanadaHonk** [comment]
To update, updater v2 continuing to receive major minor rewrites (big rewrites of smaller parts). Been working on other new things e.g. #37. Additionally, doing some major rewrites of minor internal parts like a5cf9aa. Main thing is when to mark as "completely rewritten".

**Comment by CanadaHonk** [comment]
Continual major minor rewrites occurring throughout codebase via new techniques like #49. Will mark this done soon (continual minor cleanup / rewriting will continue to happen).

**Comment by CanadaHonk** [comment]
Marking as done as it basically is.
