### ISSUE TITLE
Strange symbols in the OpenAsar update window

### ISSUE THREAD

**Issue by ivan123-tty** [GooseMod/OpenAsar#25]
Me and my friend had that issue
(screenshot by my friend)
![image](https://user-images.githubusercontent.com/70339505/156241447-d217fcb8-9b93-4a40-b49f-c74070f0a747.png)

**Comment by CanadaHonk** [comment]
Electron bug, not related to OpenAsar.

**Comment by ivan123-tty** [comment]
oh
