### ISSUE TITLE
[General] Plugins system?

### ISSUE THREAD

**Issue by CanadaHonk** [GooseMod/OpenAsar#39]
Develop plugins system to have parts of OA separated out (and allow external dev in future?)? Unsure on

**Comment by KraXen72** [comment]
doesen't this as unnecessary complexity? if somebody has a good idea they can submit a pull request to this, if it's a bad idea they can make a fork and add it there

for stuff like antilog that isn't necessary but nice to have, you could just add it as a config option, and it would not run when turned off not adding anything else than filesize, which is already extremly small.

**Comment by CanadaHonk** [comment]
The idea is to have a plugin system to have addons which are not limited by overall project goals (perf, size, tc)

**Comment by lexisother** [comment]
Eh... at this point you are authoring a client mod. Doesn't it stray a *tad* too far?

**Comment by CanadaHonk** [comment]
Client mods don't hook into asar like this nor can their plugins. Plugins would be for specialised priorities / use-cases. Still undecided.

**Comment by lexisother** [comment]
In that case I would recommend sandboxing plugins in a way that they can not go any further than making modifications to asar bits. I assume that was already on your mind, though.

**Comment by CanadaHonk** [comment]
Security-wise is complicated, yes.

**Comment by CanadaHonk** [comment]
Closing as seems overcomplicated and unnecessary, for now at least
