### ISSUE TITLE
Disconnected internet causes splash to hang

### ISSUE THREAD

**Issue by yellowsink** [GooseMod/OpenAsar#4]
If my internet is disconnected, as generally happens for me when my OS starts discord before my wifi connects, the splash will sit on checking for updates phase repeatedly, instead of just trying again after the internet re-connects, as stock app.asar does.

Screenshot of DevTools in splash:
![image](https://user-images.githubusercontent.com/19270622/147269991-8449c8a8-3a39-45d1-9f7c-babfafe42d10.png)

**Comment by CanadaHonk** [comment]
Fixed in last commit

**Comment by yellowsink** [comment]
:+1: :)
