### ISSUE TITLE
opening links in browser broken in latest nightly

### ISSUE THREAD

**Issue by KraXen72** [GooseMod/OpenAsar#5]
tired turning ssoeAllowlist on or off and also quickstart on and off still if you send an image and click open original nothing happens

**Comment by CanadaHonk** [comment]
Have you checked with normal asar? ssoeAllowlist will have no effect btw

**Comment by CanadaHonk** [comment]
Closing as heavily doubt it's OpenAsar - likely mod (other user had issue and it was PC)

**Comment by KraXen72** [comment]
i use goosemod + normal asar. maybe it is goosemod§s fault but it only started occuring once i updated the openasar nightly. and i am on goosemod stable and i didn't notice any update between when it worked and when it doesen't.

also how come you are the creator of goosemod and use powercord instead lol

**Comment by CanadaHonk** [comment]
GitHub issues isn't for support. I don't use pc, read what I actually said.

**Comment by KraXen72** [comment]
hmm okay. i will try disabling goosemod and if it is the problem ill make an issue on that repo. btw still persists on latest openasar nightly.

**Comment by CanadaHonk** [comment]
Please don't make issues for support, use the discord instead.

**Comment by KraXen72** [comment]
okay.
