### ISSUE TITLE
emoji in readme doesen't load

### ISSUE THREAD

**Issue by KraXen72** [GooseMod/OpenAsar#51]
emoji in the readme.md doesen't load in windows 10, latest vivaldi version. not a big deal, but could be replaced for a different one
![image](https://user-images.githubusercontent.com/21956756/163349836-ea622807-aafc-43c2-bc3c-653e6753fcc8.png)

**Comment by lexisother** [comment]
...that sounds like a browser / system issue. Not sure how it's a bug report for this repo.

**Comment by KraXen72** [comment]
https://github.com/GooseMod/OpenAsar/pull/52

**Comment by CanadaHonk** [comment]
That is a browser/GitHub issue as they use their own fontset.

**Comment by KraXen72** [comment]
fair enough
