### ISSUE TITLE
Unable to find version information in MacOS

### ISSUE THREAD

**Issue by thonkinator** [GooseMod/OpenAsar#58]
I was trying to find the settings menu, so after figuring out that I had to click on the OpenAsar version, I went to my settings sidebar and scrolled down. However, there is no version information for OpenAsar or any evidence that it's even there. I know I installed it, because the app.asar file is 39kb and the startup time is less than half a second.

**Comment by CanadaHonk** [comment]
Was fixed in last commit / update, reinstall OpenAsar to fully update manually if wanted.
