### ISSUE TITLE
[ThemeSync] Some themes don't sync properly (?)

### ISSUE THREAD

**Issue by yavko** [GooseMod/OpenAsar#6]
I use a theme that lives in my quickcss (in goosecord) since the version of the dracula theme i use isn't in the goosemod repos [port request](https://canary.discord.com/channels/756146058320674998/850763340313526312/925325285220569098), anyways it would be nice if the themeSync option supported quickcss options in client mods or maybe a quickcss option was added! This is probably useless to all normal users.

**Comment by CanadaHonk** [comment]
Closing as likely mostly fixed by latest rewrite.

**Comment by yavko** [comment]
can confirm it works with the theme
