### ISSUE TITLE
[NoTrack] Increases start time for some?

### ISSUE THREAD

**Issue by OzymoGit** [GooseMod/OpenAsar#60]
My stock discord startup time: 10s
OpenAsar discord startup time: 25s

What cause this? I have already delete some modules
![image](https://user-images.githubusercontent.com/33122491/167307750-6ee12295-2399-4d01-86ea-9c9063f093b0.png)
only these remain
![image](https://user-images.githubusercontent.com/33122491/167307760-a6ff53fb-d88f-4a6a-a9ab-a336d677d1f0.png)

**Comment by CanadaHonk** [comment]
You shouldn't delete modules, that's mostly reckless and will break things. Send your OpenAsar config?

**Comment by OzymoGit** [comment]
> You shouldn't delete modules, that's mostly reckless and will break things. Send your OpenAsar config?

where is the config located?

**Comment by CanadaHonk** [comment]
In `%appdata%\discord\settings.json` (presuming stable)

**Comment by OzymoGit** [comment]
![image](https://user-images.githubusercontent.com/33122491/167308126-4e7a76b2-61f4-4fd9-be1b-ac262fb0d6f2.png)
when I disable NoTrack the startup time reduce to only 7s. I think there is something wrong with NoTrack

**Comment by OzymoGit** [comment]
{
  "BACKGROUND_COLOR": "#202225",
  "IS_MAXIMIZED": true,
  "IS_MINIMIZED": false,
  "WINDOW_BOUNDS": {
    "x": 73,
    "y": 0,
    "width": 940,
    "height": 728
  },
  "OPEN_ON_STARTUP": false,
  "enableHardwareAcceleration": false,
  "openasar": {
    "setup": true,
    "quickstart": false,
    "themeSync": true,
    "noTrack": true,
    "cmdPreset": "perf"
  },
  "trayBalloonShown": true
}

**Comment by CanadaHonk** [comment]
Strange, will investigate.

**Comment by CanadaHonk** [comment]
Planning large / total rewrite of No Track at some point soon-ish which should address this.

**Comment by CanadaHonk** [comment]
Rewritten, should no longer slow down.
