### ISSUE TITLE
Doesnt work on Wayland

### ISSUE THREAD

**Issue by MGThePro** [GooseMod/OpenAsar#63]
So when running discord with OpenAsar with wayland enabled I get two discord icons in my taskbar, one on my main monitor and one on my secondary monitor. Both of these seem to not be an actual window, because the window preview is empty. When I click on them nothing happens either. Strangely they don't even show up in the preview when I alt tab. The output I get from Discord/OpenAsar doesn't seem to be any different compared to running it normally.
Regular discord with wayland has been working without issue for me so far (other than the occasional clipboard bug or lack of screenshare)
This was tested on Arch Linux with KDE Plasma 5.24.5 with Discord PTB, in case that's relevant

Steps to reproduce:
Run wayland compositor (might be reproducable in a nested session with weston for example)
install OpenAsar
run Discord with these parameters: `--enable-features=UseOzonePlatform --ozone-platform=wayland`

If you plan on comparing this to regular Discord on wayland, it might crash on the first try, but after a couple tries it will work normally, and should successfully start from the first try next time you start it

**Comment by CanadaHonk** [comment]
Can you send your `settings.json`? (probably in `~/.config/discord/settings.json`)

**Comment by MGThePro** [comment]
Sure, here they are, but I haven't actually touched any of these settings
```
{
  "BACKGROUND_COLOR": "#202225",
  "enableHardwareAcceleration": true,
  "IS_MAXIMIZED": false,
  "IS_MINIMIZED": false,
  "WINDOW_BOUNDS": {
    "x": 0,
    "y": 0,
    "width": 960,
    "height": 1018
  },
  "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true,
  "openasar": {
    "setup": true
  },
  "trayBalloonShown": true
}
```
Oh also, I forgot to mention that I have BetterDiscord installed, but it works with xorg, so I'm not sure if that has any effect

**Comment by CanadaHonk** [comment]
Add ```json
"cmdPreset": "none"
```

To the OpenAsar object

**Comment by MGThePro** [comment]
Thanks, that fixed it :+1:
