### ISSUE TITLE
[Very Low-Prio Feature Request] FOSS Reimplementation of Discord Modules

### ISSUE THREAD

**Issue by iblowmymind** [GooseMod/OpenAsar#65]
The idea in my head is that it...

- Could work with or without GooseMod (deployed from both GooseMod's update server and a custom one for OpenAsar, this could open way for OpenAsar being included in GooseMod by default).
- May include rewrite of stuff such as discord_desktop_core (which seems to have node module bloat) or audio (wouldn't be able to include Krisp, though).

Including a template to-do as well.

- [ ] Make update server for OpenAsar modules (and potential integration into GM)
- [ ] Rewrite of discord_desktop_core
- [ ] De-bloat / make the spellchecker module optional?
- [ ] Re-implement modules that are node binaries (voice, media, hook, modules...)
- [ ] Ditch JavaScript all together and re-implement Discord in Rust (joke..I hope)

**Comment by CanadaHonk** [comment]
Whilst this idea is cool it is out of scope for this project specifically. Happy to talk more in the Discord about it though.
