### ISSUE TITLE
Reload when saving a .css file

### ISSUE THREAD

**Issue by misspent** [GooseMod/OpenAsar#67]
When saving a theme.css file, discord doesn't refresh automatically like it usually does, which makes messing with your/someone else's theme a pain in the arse. I'm not sure if it's possible for you to somehow add that back to the .asar file without decreasing performance.
I would love to use this as it's small, quick, and a massive QoL, but this is the only thing stopping me from using it; however, keep up the excellent work, chief.

**Comment by CanadaHonk** [comment]
I don't remove that or anything like it. Please check it's OpenAsar and not a bug in the mod you're using?
