### ISSUE TITLE
[Feature] Customize proxy settings?

### ISSUE THREAD

**Issue by frankli0324** [GooseMod/OpenAsar#68]
### for in-app activities

it should be simple as adding

```
app.commandLine.appendSwitch('proxy-bypass-list', '<local>;*.google.com;*foo.com;1.2.3.4:5678')
app.commandLine.appendSwitch('proxy-pac-url', 'some_url')
app.commandLine.appendSwitch('proxy-server', 'some_address:some_port')
```

to `src/bootstrap.js` and adding the configurations to the config menu

or... customizable electron cmdline options?

### for bootstraping

make requests such as update operations accept the proxy settings

**Comment by CanadaHonk** [comment]
You can just do that in the command line? Or do you mean as an extra?

**Comment by frankli0324** [comment]
> You can just do that in the command line? Or do you mean as an extra?

I'm not sure what you mean... an extra to what? OpenAsar? then yes.
those are electron options, so I can't "directly" specify them

**Comment by CanadaHonk** [comment]
Yes you can, when running discord just run it with --name="value"

**Comment by frankli0324** [comment]
`./Discord` doesn't respect `--proxy-server=127.0.0.1:1234`, at least for this specific option

**Comment by CanadaHonk** [comment]
Has worked for me before so strange, will check out.

**Comment by frankli0324** [comment]
I see why I'm running into a problem. The other parts like the updater doesn't make use the proxy server... so I'm getting a "update error"

**Comment by CanadaHonk** [comment]
It would result in the same even when appending in asar, so welp.

**Comment by frankli0324** [comment]
I slightly changed my request for the feature.

**Comment by CanadaHonk** [comment]
Update operations cannot just use proxy, impossible for Windows, maybe possible for others.
