### ISSUE TITLE
Icon path for autostart .desktop file

### ISSUE THREAD

**Issue by afm0901x** [GooseMod/OpenAsar#69]
https://github.com/GooseMod/OpenAsar/blob/127236b433ae5634c832cd8f075e515ca9f838b7/src/autoStart/linux.js#L19

When using system's electron, icon path become `/usr/share/pixmaps/Discord/discord.png`.
But, Arch Linux's [discord_arch_electron](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=discord_arch_electron#n54) install icon at `/usr/share/pixmaps/discord.png`.

NOTE:
These packages use Discord's electron, but some of them install icon at `/usr/share/pixmaps/discord.png`.
 - [Arch Linux](https://archlinux.org/packages/community/x86_64/discord/) and [Solus](https://solus.pkgs.org/rolling/solus-shannon-x86_64/discord-0.0.17-24-1-x86_64.eopkg.html) - `/usr/share/pixmaps/discord.png`.
 - [Fedora](https://fedora.pkgs.org/36/rpmfusion-nonfree-x86_64/discord-0.0.17-4.fc36.x86_64.rpm.html) - `/usr/share/icons/hicolor/256x256/apps/discord.png`.

**Comment by CanadaHonk** [comment]
Fixed, thanks for report.
