### ISSUE TITLE
Asks to login everytime on startup

### ISSUE THREAD

**Issue by Paradox-77** [GooseMod/OpenAsar#7]
Discord Build: `Stable 108924 (eb8c571)`
OpenAsar Build: `Nightly - OpenAsar 1a7d927`
OpenAsar Settings: `Default (Out of the box)`
Operating System: `Windows 10 64-bit`
Modifications: `None`

Description: Discords tries to use browser hand-off key auth whenever I start discord, when that doesn't work it asks me to login manually. This happens every time I open discord but reloads work just fine. I suspect its something to do with not being able to store the credentials to disk. It's just a hunch and I don't have any evidence of it.

Steps to Reproduce: 
1. Log out to Discord
2. Install OpenAsar
3. Open Discord
4. And there you go, you're at the login page. (or it uses a browser hand off key)

**Comment by CanadaHonk** [comment]
Hey, please could you send the contents of your settings.json (`%appdata%/discord/settings.json`)? Thanks

**Comment by Paradox-77** [comment]
Sure.

```json
{
  "BACKGROUND_COLOR": "#202225",
  "IS_MAXIMIZED": true,
  "IS_MINIMIZED": false,
  "enableHardwareAcceleration": false
}
```

**Comment by CanadaHonk** [comment]
What exactly to you mean in reproduction steps? If you log out before you need to login? Could you possibly screenrecord to show? Thanks

**Comment by Paradox-77** [comment]
If you log out of discord before you install OpenAsar, it takes you to the login screen (Which of course is right). Upon logging in and then quitting discord results in the aforementioned issue. 

I accidentally bricked the client so I had to reinstall. I'll give it a go again and see if I'm still able to reproduce that.

**Comment by Paradox-77** [comment]
Okay, I reinstalled Discord again and tried to reproduce the steps, couldn't do it. It must've been something to do with that installation only. 

I'll leave the issue open so that you can close it if you want to.
