### ISSUE TITLE
[Feature] running custom js on startup

### ISSUE THREAD

**Issue by emekoi** [GooseMod/OpenAsar#71]
would it be possible to add the ability to run custom js after app initialization or would that would be out of scope for this project? if so would it be possible for me to build openasar with that extra code locally?

**Comment by lexisother** [comment]
Did you even search before opening your issue?

https://github.com/GooseMod/OpenAsar/commit/c3d6eced6c349790c7a7dc1f6bf41accb2a73f72

**Comment by CanadaHonk** [comment]
You can add
```json
"js": "<your js code>"
```

Into the OpenAsar object in your settings.json

**Comment by emekoi** [comment]
sorry, about that and thanks for the help.
