### ISSUE TITLE
Discord will not start

### ISSUE THREAD

**Issue by mobilegmYT** [GooseMod/OpenAsar#74]
I'm currently running the latest versions of Discord and OpenAsar, it worked yesterday but now refuses to start (I'm also using goosemod if that helps).

![image](https://user-images.githubusercontent.com/44128563/177008066-19b0ae4d-e1b6-41e5-b9e3-693e7572534b.png)

**Comment by CanadaHonk** [comment]
Please use [the Discord](https://discord.com/invite/neMncS2) for support, thanks.
