### ISSUE TITLE
[Bug] Slower channel switch on low end devices

### ISSUE THREAD

**Issue by MeFinity** [GooseMod/OpenAsar#76]
Switching channels/direct messages is very slow on lower end devices
Well,discord is slower overall,the only page that is not experiencing a slow down is the settings page

OS: Windows 10
Mod: Powercord

**Comment by MeFinity** [comment]
it is noticeably slower,it feels like i have 200 tabs open in chrome

**Comment by CanadaHonk** [comment]
Try changing the focus option to balanced, or without your mod.

**Comment by MeFinity** [comment]
unplugging Powercord and replugging it would seem to fix the issue
do you know why this would happen?

sorry for wasting your time,have a good day

**Comment by CanadaHonk** [comment]
We don't touch or make Powercord, so don't know. It's fine, and thanks.
