### ISSUE TITLE
Idk where is openasar version

### ISSUE THREAD

**Issue by dibusure** [GooseMod/OpenAsar#78]
guys, if i really stupid, please sorry me
![image](https://user-images.githubusercontent.com/69085213/184017483-88d0eaee-74f2-4b94-8ceb-791b7f81669a.png)
idk where is openasar version, where i can click and configurate

**Comment by CanadaHonk** [comment]
You don't have OpenAsar installed, you need to reinstall it with Linux updates (out of my control).

**Comment by dibusure** [comment]
hey @CanadaHonk, i installed openasar
downloaded app.asar
moved it to `/opt/discord/resources/` (`mv app.asar /opt/discord/resources/app.asar`)
and restarted discord
what's wrong?

**Comment by dibusure** [comment]
u can see it here
![image](https://user-images.githubusercontent.com/69085213/184018456-39f19a1a-42ee-496d-af1d-bbcdc7810c80.png)

**Comment by CanadaHonk** [comment]
Did you restart Discord via system tray?

**Comment by dibusure** [comment]
yup

**Comment by dibusure** [comment]
2 billion times

**Comment by CanadaHonk** [comment]
Can you `killall discord` and start `discord` in your terminal, and screenshot?

**Comment by dibusure** [comment]
one minute

**Comment by dibusure** [comment]
well i can paste log in pastebin

**Comment by CanadaHonk** [comment]
Just screenshot the first outputs.

**Comment by dibusure** [comment]
@CanadaHonk 
![image](https://user-images.githubusercontent.com/69085213/184019659-b6dd027f-40b9-4017-b928-1b23207487b9.png)

**Comment by CanadaHonk** [comment]
You don't have OpenAsar installed.

**Comment by dibusure** [comment]
and how can i install it?

**Comment by dibusure** [comment]
if just move dont work?

**Comment by CanadaHonk** [comment]
You probably didn't have permissions so it didn't copy properly, use sudo.

**Comment by dibusure** [comment]
i used sudo

**Comment by dibusure** [comment]
well i try recopy

**Comment by dibusure** [comment]
@CanadaHonk what should app.asar folder look like with openasar properly installed

**Comment by dibusure** [comment]
![image](https://user-images.githubusercontent.com/69085213/184021252-db560b74-f723-4594-bbc1-68570c86b40d.png)
this is my folder

**Comment by dibusure** [comment]
finally

**Comment by dibusure** [comment]
thanks @CanadaHonk, i reinstalled and it works

**Comment by CanadaHonk** [comment]
Cool

**Comment by dibusure** [comment]
closed
