### ISSUE TITLE
[Question] Uninstall

### ISSUE THREAD

**Issue by zachjmurphy** [GooseMod/OpenAsar#82]
How do I uninstall OpenAsar? The wiki & readme doesn't say how to uninstall.

**Comment by CanadaHonk** [comment]
Forgot to add to wiki (is pinned in Discord).

For Windows:
- Press Win + R, paste in %localappdata%\Discord\app-1.0.9006\resources
- Download https://asar.goose.icu/asar/latest as app.asar there (or download, then overwrite app.asar)

**Comment by zachjmurphy** [comment]
Awesome! Thank You. A cool feature to the installer would be a uninstall feature.
