### ISSUE TITLE
When clicking OpenAsar text to open the settings, the cursor is on the text selecting state

### ISSUE THREAD

**Issue by RaptaG** [GooseMod/OpenAsar#85]
Instead of:
![](https://user-images.githubusercontent.com/77157639/193039280-0c56bdb8-4bf3-4093-a008-733b6a151619.png)
It shows this:
![](https://user-images.githubusercontent.com/77157639/193039627-e49436f4-6271-4ed3-a069-c6485e6ea1c1.png)

**Comment by CanadaHonk** [comment]
Bug from last release, pushed fix.
