### ISSUE TITLE
With Disable Typing

### ISSUE THREAD

**Issue by thiaguinho4** [GooseMod/OpenAsar#89]

**Comment by botatooo** [comment]
lol

**Comment by thiaguinho4** [comment]
with disable typing enabled then show the typing status in groups
![1](https://user-images.githubusercontent.com/101910294/193374705-3be42e02-6d68-42c1-a5be-15dc448882cf.png)

**Comment by CanadaHonk** [comment]
GitHub Issues isn't for support. It shows locally but isn't actually sent out.
