### ISSUE TITLE
[FEATURE] Allow experimental custom scripts.

### ISSUE THREAD

**Issue by BlueFalconHD** [GooseMod/OpenAsar#90]
These would just be basic javascript injected into the window at startup. No sandboxing, just injection. They could use whatever method they want of getting info. If someone decides to make a plugin store that can install others, cool!

**Comment by CanadaHonk** [comment]
Already exists as `"js"` key in OA config (similar to CSS, just no UI).

**Comment by CanadaHonk** [comment]
It injects the given string into the main window like a script.

**Comment by BlueFalconHD** [comment]
> It injects the given string into the main window like a script.

So it has full access to whatever Discord is able to access, right?
