### ISSUE TITLE
OpenAsar config window is broken when light mode is turned on

### ISSUE THREAD

**Issue by UrkiMimi** [GooseMod/OpenAsar#92]
I have OpenAsar both installed on my PC and Chromebook and was about to edit some settings when I noticed light mode completely breaks the config window. I had light mode turned on while using my Chromebook.
![image](https://user-images.githubusercontent.com/74517821/193425954-593811c1-e33f-4ad8-ada6-bed4b43bdd2c.png)

**Comment by xemulat** [comment]
it works on windows

![image](https://user-images.githubusercontent.com/98595166/196604256-3fa14616-b139-411e-bf50-70a7ca38b621.png)

**Comment by xemulat** [comment]
same issue on Windows

![image](https://user-images.githubusercontent.com/98595166/196604333-4580e8ee-9990-48a7-8c0b-b472a182529f.png)

**Comment by CanadaHonk** [comment]
Fixed.
