### ISSUE TITLE
OpenAsar for Discord Development?

### ISSUE THREAD

**Issue by DavidNyan10** [GooseMod/OpenAsar#93]
It currently only has download links for Stable, PTB and Canary. It'd be great if it supported Development.

**Comment by DavidNyan10** [comment]
I think it'd be great to have it on the website too.

**Comment by CanadaHonk** [comment]
It isn't on the website as Discord development isn't an official (ly recognised) client so has a higher chance of generally breaking. I'll consider adding it later.

**Comment by DavidNyan10** [comment]
Damn, it's more stable than canary tho XD

**Comment by CanadaHonk** [comment]
It isn't more stable.

**Comment by DavidNyan10** [comment]
Huh? I feel like Canary breaks more often than Development. I've been using GooseMod on Dev for around 5 months now, and still haven't had to reinstall or wait for a new update. I can't tell if it's just GooseMod being so good, but I've read somewhere Development receives the same updates as PTB. Might be wrong, haven't checked but at least Dev doesn't get 27 updates in a day shuffling class names.

**Comment by CanadaHonk** [comment]
Your information is wrong, Development loads the same webapp as Canary (it says Canary in settings), so yes it would get the same updates as Canary. The only difference is host updates. It is less stable, mods breaking less often != stable. No one should really use Development.

**Comment by DavidNyan10** [comment]
Ahh I see, thank you! I was just confused as GooseMod had Development as an install option.

**Comment by CanadaHonk** [comment]
GooseMod wasn't a rewrite of part of it, just on top so Development didn't really effect it.
