### ISSUE TITLE
How the hell do I uninstall this?!

### ISSUE THREAD

**Issue by TEnLOcODE** [GooseMod/OpenAsar#94]
I installed OpenAsar like.. 3 days ago.. 
And I want to uninstall it now.
How do I do it?!

**Comment by kristiankunc** [comment]
go to `%localappdata%\Discord\app-x.x.xxxx\resources\app.asar` (xxx version, currently 1.0.9006)
you should see `app.asar` & `app.asar.backup` --> delete **app.asar** and rename **app.asar.backup** to **app.asar**

**Comment by CanadaHonk** [comment]
https://github.com/GooseMod/OpenAsar/wiki/Install-Guide#uninstall
