### ISSUE TITLE
I can't change the openasar setting

### ISSUE THREAD

**Issue by CoolJosh0221** [GooseMod/OpenAsar#95]
After I first installed openasar, it showed a setting panel
But when I restarted it i can't find the setting panel

**Comment by CoolJosh0221** [comment]
and the there is no config window at the bottom of the sidebar

**Comment by JetpackJackson** [comment]
I have the same question. Did you figure out where to configure it?

**Comment by CanadaHonk** [comment]
Use the Discord server for support (https://openasar.dev)

**Comment by AJolly** [comment]
In Discord, go to settings.  Way at the bottom where it says the version number in small print - 
it'll look like "Stable 174051 (5996312) Host 1.0.9010 (29128) | OpenAsar 40b27dd Windows 10 64-Bit (10.0.19045)"

Click on OpenASAR. 

Took me a bit to find, hopefully this helps someone else.
