### ISSUE TITLE
Self-updater

### ISSUE THREAD

**Issue by RaptaG** [GooseMod/OpenAsar#97]
OpenAsar should be able to update by itself automatically (togglable) and/or show a notification when an update is available.

**Comment by CanadaHonk** [comment]
Already exists, see faq.md

**Comment by RaptaG** [comment]
I also have another question.. According to the FAQ, I can use it with other Discord mods right? Will Replugged work?

**Comment by CanadaHonk** [comment]
It works with other mods, but Replugged itself was broken by a Discord update.
