### ISSUE TITLE
on performance mode you cant solve hCaptchas

### ISSUE THREAD

**Issue by MrEnoX** [GooseMod/OpenAsar#98]
when you try to solve hChaptcha it turns gray. It never comes back. This issue is only on performance mode. 

![image](https://user-images.githubusercontent.com/97337724/194779653-0a48cb0d-f49e-4f06-957a-aa68388ec19a.png)

**Comment by CanadaHonk** [comment]
Please check https://github.com/GooseMod/OpenAsar/issues/57
