### ISSUE TITLE
Discord with OpenAsar not respecting GTK theme on Linux

### ISSUE THREAD

**Issue by Sir-Photch** [GooseMod/OpenAsar#99]
I have noticed that since I have installed openasar, discord does not respect the gtk-theme of my gnome desktop, which is set to adwaita-dark. This should result in a dark title bar:

![grafik](https://user-images.githubusercontent.com/47949835/194941404-a77d770d-4abc-4504-8b41-976eb4bffe5a.png)

You can see how it is supposed to look on the left window.

**Comment by CanadaHonk** [comment]
OpenAsar doesn't touch the main window or the titlebar, etc. It is likely an issue elsewhere.
